server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://120.78.57.208:3308/keshe?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: xmutkeshe
    driver-class-name: com.mysql.jdbc.Driver
